### ISSUE TITLE
Prefer cson over yaml?

### ISSUE THREAD

**Issue by harlantwood** [ipfs/ipld-examples#1]
[CSON](https://github.com/bevry/cson) is a very nice superset of (well formatted) JSON, which notably allows for comments.  I prefer it over yaml myself, so wanted to make sure you're aware of it @jbenet ... Ultimately just a color preference tho.

**Comment by harlantwood** [comment]
Note that you can use curly braces, quotes and commas exactly like JSON, and add comments... That's how I imagine it might get used in these examples.

**Comment by jbenet** [comment]
@harlantwood yeah this[0] CSON is great! I'm a fan. I used yml because some others in the community like using yml, and it's standard enough. (CSON is not as widely deployed / recognizable yet). In the end ipld will support all of these. feel free to add some examples using CSON. we should feel comfortable defining objects in all of these formats so that we make user lots of users have a wonderful UX

[0] there's a few others i think

**Comment by rvagg** [comment]
closing for archival
